CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  fullName TEXT NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  sid TEXT PRIMARY KEY,
  expires INTEGER,
  data TEXT
);

CREATE TABLE IF NOT EXISTS pages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS pagesContent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pageId INTEGER NOT NULL,
  language TEXT NOT NULL,
  data TEXT NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pageId) REFERENCES pages(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS news (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  published BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS newsContent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  newsId INTEGER NOT NULL,
  language TEXT NOT NULL,
  title TEXT NOT NULL,
  data TEXT NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (newsId) REFERENCES news(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS staff (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  published BOOLEAN DEFAULT FALSE,
  slug TEXT,
  email TEXT,
  phone TEXT,
  orderIndex INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS staffContent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  staffId INTEGER NOT NULL,
  language TEXT NOT NULL,
  name TEXT NOT NULL,
  position TEXT,
  data TEXT NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (staffId) REFERENCES staff(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS specialties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS specialtyContent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  specialtyId INTEGER NOT NULL,
  language TEXT NOT NULL,
  name TEXT NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (specialtyId) REFERENCES specialties(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS studentMaterials (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  specialtyId INTEGER NOT NULL,
  course INTEGER NOT NULL,
  FOREIGN KEY (specialtyId) REFERENCES specialties(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS studentMaterialsContent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  materialId INTEGER NOT NULL,
  language TEXT NOT NULL,
  data TEXT NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (materialId) REFERENCES studentMaterials(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  originalFilename TEXT NOT NULL,
  mimetype TEXT NOT NULL,
  size INTEGER NOT NULL,
  filepath TEXT NOT NULL,
  path TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pagesFile (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fileId INTEGER NOT NULL,
  pageId INTEGER NOT NULL,
  FOREIGN KEY (fileId) REFERENCES files(id) ON DELETE CASCADE,
  FOREIGN KEY (pageId) REFERENCES pages(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS newsFile (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fileId INTEGER NOT NULL,
  newsId INTEGER NOT NULL,
  FOREIGN KEY (fileId) REFERENCES files(id) ON DELETE CASCADE,
  FOREIGN KEY (newsId) REFERENCES news(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS staffFile (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fileId INTEGER NOT NULL,
  staffId INTEGER NOT NULL,
  FOREIGN KEY (fileId) REFERENCES files(id) ON DELETE CASCADE,
  FOREIGN KEY (staffId) REFERENCES staff(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS studentMaterialsFile (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fileId INTEGER NOT NULL,
  materialId INTEGER NOT NULL,
  FOREIGN KEY (fileId) REFERENCES files(id) ON DELETE CASCADE,
  FOREIGN KEY (materialId) REFERENCES studentMaterials(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS contacts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL,
  value TEXT NOT NULL
);
